import React from "react";

function Home() {
  return (
    <div>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
      <h1>THERE IS NO PLACE LIKE A HOME !</h1>
    </div>
  );
}

export default Home;
